In [17]:
import tensorflow as tf

## constant

In [90]:
scalar = tf.constant(42)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])

In [18]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [92]:
tensor=tf.constant([[1, 2], [3, 4]])
# dimensions 
tensor_shape = tf.shape(tensor)
print(tensor_shape)

# How many dimensions are in the tensor? :rank
tensor_rank = tf.rank(tensor)
print(tensor_rank)
# elements 
tensor_size = tf.size(tensor)
print(tensor_size)

tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [72]:
x.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [19]:
y=tf.constant(12)
print(y)

tf.Tensor(12, shape=(), dtype=int32)


In [20]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(2,3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [21]:
#datatype change
dc_x=tf.cast(x,dtype=tf.float32)
print(dc_x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


## operators

In [ ]:
# for square root it should be float type.
a=tf.constant([2],dtype=tf.float32)
print(tf.sqrt(a))

In [32]:
a=tf.constant([1,2,3])
b=tf.constant([9,8,7])
res=tf.add(a,b)
res

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [35]:
res=a+b
res

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [36]:
tf.subtract(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [37]:
tf.multiply(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [39]:
tf.divide(a,b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [40]:
tf.pow(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([   1,  256, 2187], dtype=int32)>

In [44]:
a_cast=tf.cast(a,dtype=tf.float32)
tf.exp(a_cast)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)>

In [45]:
tf.sqrt(a_cast)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

In [47]:
a=tf.constant([[1,2],[4,5]])
b=tf.constant([[1,2],[4,5]])
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]], dtype=int32)>

## indexing


In [52]:
print(a[:])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [53]:
a[1:]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 5]], dtype=int32)>

In [54]:
a[1:2]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 5]], dtype=int32)>

In [55]:
a[::-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2]], dtype=int32)>

## reshape

In [59]:
x=tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [58]:
tf.reshape(x,(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [62]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
x_transposed = tf.transpose(x, perm=[1, 0])
print(x_transposed)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## Variables - trainable

In [64]:
v=tf.Variable(1.0)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


In [66]:
v.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [67]:
v.assign_add(3)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=5>

In [93]:
v.assign_sub(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1>

In [95]:

def simple_function(x):
    return x**2

loss = simple_function(v)


In [97]:
with tf.GradientTape() as tape:
   
    loss = simple_function(v)

# Compute gradients
gradients = tape.gradient(loss, [v])


print("Gradients with respect to v:", gradients)


Gradients with respect to v: [None]
